name: Python Code Quality (SPEI Governance)

# Se ejecuta en cada push o pull request a la rama principal
on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  lint:
    name: Syntax and Style Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Verificación de errores de sintaxis críticos (Gobernanza)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Advertencias de estilo (opcional para limpieza de código)
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Audit Trail Notification
      run: echo "Audit check completed for Solution Project Leader: Luciano Jimenez"